#index:
#    path: /
#    controller: App\Controller\DefaultController::index
lieux:
  path: /lieux
  defaults:
    _api_resource_class: App\Entity\Lieu
login:
  path: /login
  methods: ["POST"]
api_login_check:
  path: /login_check
# authentication_token:
#   path: /authentication_token
#   methods: ["POST"]
